{pkgs, ...}:
# Complete setup guide for Hydenix NixOS system configuration
# Edit the marked REQUIRED sections below, then run: nixos-rebuild switch --flake .#default
{
  imports = [
    ./modules/system # Custom system-level modules
    ./hardware-configuration.nix # Hardware config generated by nixos-generate-config
  ];

  # Home Manager: Manages user-level configuration (shells, dotfiles, applications)
  # REQUIRED: Change "hydenix" to your actual username (must match users.users below)
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users."hydenix" = import ./modules/hm;
  };

  # User Account Configuration
  # REQUIRED: Change "hydenix" to your desired username (must match home-manager config above)
  users.users.hydenix = {
    isNormalUser = true;
    initialPassword = "hydenix"; # SECURITY: Change immediately with `passwd` after first login
    extraGroups = [
      "wheel" # Sudo access
      "networkmanager" # Network management
      "video" # GPU/display access
    ];
    shell = pkgs.zsh; # Choose: pkgs.bash, pkgs.zsh, pkgs.fish
  };

  # Hydenix Desktop Environment Configuration
  hydenix = {
    enable = true;
    # Customize these three settings
    hostname = "hydenix"; # Network hostname (should be unique on your network)
    timezone = "America/Vancouver"; # See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    locale = "en_CA.UTF-8"; # System language and encoding
    # Additional options available in: ./docs/options.md
  };

  # NixOS State Version: Ensures compatibility during system upgrades
  # Only increment when deliberately migrating to a new NixOS release
  system.stateVersion = "25.05";
}
