name: Flake Check

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  schedule:
    - cron: '0 3 * * 1'

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Root Flake
        run: nix flake check

      - name: Check Template Flake
        run: |
          cd template
          sed -i 's|url = "github:florianvazelle/hydenix"|url = "path:../"|' flake.nix
          nix flake check
          git checkout flake.nix
          rm -f flake.lock
