name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:

permissions: {}

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate renovate config
        run: nix-shell -p renovate --run "renovate-config-validator --strict"

  renovate-local:
    runs-on: ubuntu-latest
    environment: renovate
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Sets env var for dry-run
        if: github.event_name == 'pull_request'
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_ALLOWED_COMMANDS: '["^nix run github:Mic92/nix-update -- ", "^nix flake lock$"]'
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
